### ISSUE TITLE
related dataset

### ISSUE THREAD

**Issue by shwetaqueen** [fescobar96/Tracking-Water-Levels-in-Satellite-Images#1]
data related to past flood events, including the dates, locations, water gauge levels, and any available images or satellite imagery of the flooded areas. This data will be used to train and validate your AI-ML model  we required for smart india hackathon project  can you help  me

**Comment by fescobar96** [comment]
@shwetaqueen, everything you need is in the repo. Feel free to let me know if you run into issues or have specific questions. Thanks!
